### ISSUE TITLE
Kernel build error

### ISSUE THREAD

**Issue by Aro2142** [edk2-porting/edk2-sm7150#1]
Hi, thanks for the port provided, but I'm having problems building the kernel. Error in "build" file, line 14 (or 13, I don't remember XD) on path ../edk2/BaseTools/BinWrappers/PosixLike/build.
Before that I downloaded and installed everything I needed, and also used different instructions that I could find in "edk2-porting", but to no avail, maybe I'm just stupid XD.
PS: there were attempts to build the kernel on different OS: Android, Debian, including Ubuntu. Kernel assembly for Snapdragon 845 was successful.

Could you please help me or describe your build method and what conditions are required for this.
(Translated from Russian to English, so don't scold for mistakes :))

Learn more about the problem:
Loading previous configuration from /home/arowhite/workspaceedk2/edk2-sm7150/../edk2/Conf/BuildEnv.sh
Using EDK2 in-source Basetools
WORKSPACE: / home / arowhite / workspaceedk2 / edk2-sm7150 /
EDK_TOOLS_PATH: /home/arowhite/workspaceedk2/edk2-sm7150/../edk2/BaseTools
CONF_PATH: /home/arowhite/workspaceedk2/edk2-sm7150/../edk2/Conf
/home/arowhite/workspaceedk2/edk2-sm7150/../edk2/BaseTools/BinWrappers/PosixLike/build: line 14: exec: python: not found

**Comment by sunflower2333** [comment]
Install python 2.7.
cd edk2/BaseTools/Source/C && make

**Comment by sunflower2333** [comment]
remember to edit build.sh to set correct dtb and cross cpmile.
