### ISSUE TITLE
F11.dsc(...): error 4000: Instance of library class [RegisterFilterLib] is not found

### ISSUE THREAD

**Issue by S-8506** [edk2-porting/edk2-sm7150#2]
Loading previous configuration from /home/codenaive/Desktop/EDK/edk2-sm7150/sm7150N/../edk2/Conf/BuildEnv.sh
Using EDK2 in-source Basetools
WORKSPACE: /home/codenaive/Desktop/EDK/edk2-sm7150/sm7150N/
EDK_TOOLS_PATH: /home/codenaive/Desktop/EDK/edk2-sm7150/sm7150N/../edk2/BaseTools
CONF_PATH: /home/codenaive/Desktop/EDK/edk2-sm7150/sm7150N/../edk2/Conf
Build environment: Linux-5.11.0-36-generic-x86_64-with-glibc2.29
Build start time: 22:31:37, Oct.15 2021

WORKSPACE        = /home/codenaive/Desktop/EDK/edk2-sm7150/sm7150N
PACKAGES_PATH    = /home/codenaive/Desktop/EDK/edk2-sm7150/edk2:/home/codenaive/Desktop/EDK/edk2-sm7150/edk2-platforms:/home/codenaive/Desktop/EDK/edk2-sm7150/sm7150N
EDK_TOOLS_PATH   = /home/codenaive/Desktop/EDK/edk2-sm7150/sm7150N/../edk2/BaseTools
CONF_PATH        = /home/codenaive/Desktop/EDK/edk2-sm7150/edk2/Conf
PYTHON_COMMAND   = python2.7

Processing meta-data 
.Architecture(s)  = AARCH64
Build target     = DEBUG
Toolchain        = GCC5

Active Platform          = /home/codenaive/Desktop/EDK/edk2-sm7150/sm7150N/F11/F11.dsc
................

build.py...
/home/codenaive/Desktop/EDK/edk2-sm7150/sm7150N/F11/F11.dsc(...): error 4000: Instance of library class [RegisterFilterLib] is not found
	in [/home/codenaive/Desktop/EDK/edk2-sm7150/edk2/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic.inf] [AARCH64]
	consumed by module [/home/codenaive/Desktop/EDK/edk2-sm7150/edk2/ArmPlatformPkg/PrePi/PeiUniCore.inf]
 

- Failed -
Build end time: 22:31:54, Oct.15 2021
Build total time: 00:00:18

**Comment by MollySophia** [comment]
This have been fixed in the latest commit.
