### ISSUE TITLE
redmiK20.img

### ISSUE THREAD

**Issue by romario056** [edk2-porting/edk2-sm7150#3]
As we can see, its possible. But when i tried to make it works, i have the same error 4000.
May be develover can post the .img for any devices?
My clone-repository is not work well.

**Comment by MollySophia** [comment]
This have been fixed in the latest commit.

**Comment by romario056** [comment]
Really?
Since half year )
Actually now I know about it)

**Comment by MollySophia** [comment]
This repository has been private until 2 days ago, so yeah.

**Comment by romario056** [comment]
Tx
